### ISSUE TITLE
Setup a proper CI using GitHub actions

### ISSUE THREAD

**Issue by gabrielPeart** [shortcut/shortcut-foundation-ios#32]
- Build the project
- Run the tests
- Lint the project

`The CI must be run when we open a pull request and write a comment as a trigger to run the job`

**Comment by lemonandlime** [comment]
I spent a couple of hours on this in October but did not get it to work properly. CircleCI took 10 minutes.

**Comment by gabrielPeart** [comment]
> I spent a couple of hours on this in October but did not get it to work properly. CircleCI took 10 minutes. 

I did set it up on my private projects and it took 10 minutes using GitHub actions. There are lots of open source Swift packages as well using only GitHub actions. Maybe something was set up wrongly when you tested it.

**Comment by lemonandlime** [comment]
Great lets go for it agan then. I think the missing part back then was that I could not specify Xcode version and that was really important for 13.1 vs 13.2

**Comment by KhoiNguyenShortcut** [comment]
Hi @gabrielPeart, @lemonandlime 

I just try to setup a workflow with Github Action and create a PR here: https://github.com/shortcut/shortcut-foundation-ios/pull/46

Please take a look,
Thank you
